language: java
jdk:
- oraclejdk8
- openjdk8
script:
- jdk_switcher use oraclejdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build"
- "./gradlew javadoc"
- jdk_switcher use openjdk8
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew build"
- "./gradlew javadoc"
- "./gradlew jar"
- "./gradlew shadowJar"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
#env:
#  global:
#  - FTPUSER=xxxxx
#  - FTPPWD=xxxxxx
#  - FTPSERVER=xxxxx
#after_success:
#  - find docs/ -type f -exec curl -u ${FTPUSER}:${FTPPWD} --ftp-create-dirs -T {} ftp://${FTPSERVER}/{} \;